# Generated by Django 5.1 on 2024-08-27 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenseTracker', '0004_alter_expense_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='currency',
            field=models.CharField(choices=[('usd', 'US Dollar $'), ('eur', 'Euro €'), ('gbp', 'Great Britain Pound £'), ('jpy', 'Japan Yen ¥'), ('aud', 'Australian Dollar $'), ('cad', 'Canadian Dollar $'), ('krw', 'Korean Won ₩'), ('inr', 'Indian Rupee ₹')], default='usd', max_length=3),
        ),
        migrations.AlterField(
            model_name='expense',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
