# Generated by Django 5.1 on 2024-09-02 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenseTracker', '0006_remove_expense_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='end_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='start_date',
        ),
    ]
