# Generated by Django 5.1 on 2024-11-20 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenseTracker', '0009_alter_expense_category_delete_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='recurring',
            field=models.CharField(blank=True, default=None, max_length=7, null=True),
        ),
    ]
