# Generated by Django 5.1 on 2024-11-20 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenseTracker', '0013_alter_expense_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='frequency',
            field=models.CharField(blank=True, default=None, max_length=8, null=True),
        ),
    ]
