# Generated by Django 5.1 on 2024-11-20 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenseTracker', '0014_alter_expense_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='frequency',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
