# Generated by Django 5.1 on 2024-11-20 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenseTracker', '0016_alter_expense_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='period',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
    ]
