# Generated by Django 5.1.3 on 2025-12-26 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenseTracker', '0023_alter_expense_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='placeholder', max_length=150)),
                ('type', models.CharField(choices=[('Expense', 'Expense'), ('Income', 'Income')], max_length=15)),
                ('category', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(choices=[('usd', 'US Dollar $'), ('eur', 'Euro €'), ('gbp', 'Great Britain Pound £'), ('jpy', 'Japan Yen ¥'), ('aud', 'Australian Dollar $'), ('cad', 'Canadian Dollar $'), ('krw', 'Korean Won ₩'), ('inr', 'Indian Rupee ₹')], default='usd', max_length=3)),
                ('frequency', models.CharField(blank=True, choices=[('monthly', 'monthly'), ('yearly', 'yearly'), (None, 'None')], max_length=10, null=True)),
                ('period', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Expense',
        ),
    ]
