# Generated by Django 5.1.3 on 2025-12-29 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenseTracker', '0024_transaction_delete_expense'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_budget', models.IntegerField(blank=True, null=True)),
                ('display_currency', models.CharField(max_length=3)),
                ('display_timezone', models.CharField(blank=True, max_length=50, null=True)),
                ('display_date_format', models.CharField(blank=True, max_length=20, null=True)),
                ('display_dashboard_range', models.CharField(choices=[('month', 'month'), ('quarter', 'quarter'), ('year', 'year'), ('all', 'all')], default='month', max_length=10)),
                ('notifcations_enabled', models.BooleanField(default=False)),
                ('income_affects_budget', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
