# Generated by Django 5.1.3 on 2025-12-29 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenseTracker', '0025_usersettings_delete_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersettings',
            old_name='notifcations_enabled',
            new_name='notifications_enabled',
        ),
        migrations.AddField(
            model_name='usersettings',
            name='category_budget_limits',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='over_spending_threshold',
            field=models.DecimalField(decimal_places=2, default=0.8, max_digits=5),
        ),
    ]
