# Generated by Django 5.1.3 on 2025-12-29 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenseTracker', '0029_alter_usersettings_display_dashboard_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='display_dashboard_range',
            field=models.CharField(choices=[('Current Month', 'Current Month'), ('30 Days', '30 Days'), ('Quarter', 'Quarter'), ('Year', 'Year'), ('All', 'All')], default='Current Month', max_length=20),
        ),
    ]
