# Generated by Django 5.1.3 on 2026-01-03 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenseTracker', '0030_alter_usersettings_display_dashboard_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='income_ratio_for_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
