# Generated by Django 5.1 on 2024-08-30 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personalFinanceDashboard', '0005_expense_currency_alter_expense_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='description',
        ),
    ]
