# Generated by Django 5.1 on 2024-09-02 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalFinanceDashboard', '0007_rename_end_date_expense_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='name',
            field=models.CharField(default='placeholder', max_length=150),
        ),
    ]
