# Generated by Django 5.1 on 2024-09-11 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalFinanceDashboard', '0008_expense_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(max_length=150),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
