# Generated by Django 5.1 on 2024-11-20 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalFinanceDashboard', '0010_expense_recurring'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(blank=True, default=None, max_length=150),
        ),
    ]
