# Generated by Django 5.1 on 2024-11-20 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personalFinanceDashboard', '0011_alter_expense_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='recurring',
            new_name='frequency',
        ),
    ]
