# Generated by Django 5.1 on 2024-11-20 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalFinanceDashboard', '0012_rename_recurring_expense_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
    ]
