# Generated by Django 5.1 on 2024-11-20 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalFinanceDashboard', '0015_alter_expense_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='frequency',
            field=models.CharField(blank=True, choices=[('Monthly', 'Monthly'), ('Yearly', 'Yearly'), (None, 'None')], max_length=10, null=True),
        ),
    ]
