# Generated by Django 5.1 on 2025-01-15 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personalFinanceDashboard', '0018_alter_expense_frequency_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='budget_limit',
            new_name='monthly_budget',
        ),
    ]
