# Generated by Django 5.1.3 on 2025-12-29 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personalFinanceDashboard', '0026_rename_notifcations_enabled_usersettings_notifications_enabled_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='display_timezone',
        ),
    ]
