# Generated by Django 5.1.3 on 2025-12-29 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalFinanceDashboard', '0027_remove_usersettings_display_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='display_dashboard_range',
            field=models.CharField(choices=[('current month', 'current month'), ('30days', '30days'), ('quarter', 'quarter'), ('year', 'year'), ('all', 'all')], default='current month', max_length=20),
        ),
    ]
