# Generated by Django 5.1.3 on 2026-01-05 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalFinanceDashboard', '0031_usersettings_income_ratio_for_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='income_ratio_for_budget',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
    ]
